exports.lab = require('lab').script();
const {describe, it} = require('../setup')
const Lock = require('../../src/models/lock')

describe('Lock model', function() {
  it("can be created", ()=>{

  })
  it("can be destroyed", ()=>{

  })
  it("name can be patched", ()=>{

  })
  it("contains reference to a user", ()=>{

  })
  it("macId is autogenerated", ()=>{

  })
});