const { expect } = require('code');
const Lab = require('lab');
const {afterEach, describe, it } = exports.lab = Lab.script();

const Lock = require('../../src/models/lock')

describe('Lock model', function() {
  it("can be created", ()=>{

  })
  it("can be destroyed", ()=>{

  })
  it("name can be patched", ()=>{

  })
  it("contains reference to a user", ()=>{

  })
  it("macId is autogenerated", ()=>{

  })
});