# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.0.0
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: yarn test
    
  deploy-master:
     machine:
        enabled: true
     working_directory: ~/repo
     environment:
       HEROKU_APP: "lattis-hapi"
     steps:
       - checkout
       - run:
           name: Deploy Master to Heroku
           command: |
             git push https://mitzsuyi:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP.git  master   
             
  deploy-dev:
    machine:
        enabled: true
    working_directory: ~/repo
    environment:
      HEROKU_APP: "lattis-hapi"
    steps:
      - checkout
      - run:
          name: Deploy Development to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP.git master
            
workflows:
  version: 2
  lattis-workflow:
    jobs:
       - deploy-dev:
           context: lattis-hapi-deploy
           requires: 
             - build                  
           filters:
             branches:
               only: staging
                 
       - deploy-master:
            context: lattis-hapi-deploy
            requires: 
              - build         
            filters:  # using regex filters requires the entire branch to match
              branches:
                only: 
                  - master        
       - build:
           context: lattis-hapi-tests      
     
